# Generated by Django 4.2 on 2026-05-06 01:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsProcedure',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد رویه')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام رویه')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان رویه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'رویه گمرکی',
                'verbose_name_plural': 'رویه\u200cهای گمرکی',
                'db_table': 'tirpark_customs_procedures',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='نام کامل')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='اولین مشاهده')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخرین مشاهده')),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'رانندگان',
                'db_table': 'tirpark_drivers',
            },
        ),
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('load_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='شناسه بار')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بار')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'نوع بار',
                'verbose_name_plural': 'انواع بار',
                'db_table': 'tirpark_load_types',
            },
        ),
        migrations.CreateModel(
            name='ParkingQueue',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='شناسه')),
                ('receipt_number', models.CharField(db_index=True, max_length=100, verbose_name='شماره رسید')),
                ('status', models.CharField(choices=[('in', 'در پارکینگ'), ('out', 'خارج شده'), ('waiting', 'در انتظار'), ('processing', 'در حال بررسی')], db_index=True, default='in', max_length=20, verbose_name='وضعیت')),
                ('transit_number_plate', models.CharField(blank=True, max_length=50, null=True, verbose_name='پلاک ترانزیت')),
                ('number_plate_json', models.TextField(blank=True, null=True, verbose_name='JSON پلاک')),
                ('entry_date_time', models.DateTimeField(verbose_name='زمان ورود')),
                ('exit_date_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('entry_jdate', models.CharField(max_length=50, verbose_name='تاریخ ورود (جلالی)')),
                ('exit_jdate', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ خروج (جلالی)')),
                ('entry_gdate', models.CharField(max_length=50, verbose_name='تاریخ ورود (میلادی)')),
                ('exit_gdate', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ خروج (میلادی)')),
                ('load_id', models.CharField(max_length=50, verbose_name='شناسه بار')),
                ('load_title', models.CharField(max_length=200, verbose_name='عنوان بار')),
                ('imperative', models.BooleanField(default=False, verbose_name='ضروری')),
                ('truck_model_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل کامیون')),
                ('killer_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع کیلر')),
                ('is_synced', models.BooleanField(default=True, verbose_name='همگام\u200cسازی شده')),
                ('sync_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ همگام\u200cسازی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'صف پارکینگ',
                'verbose_name_plural': 'صف\u200cهای پارکینگ',
                'db_table': 'tirpark_parking_queue',
                'ordering': ['-entry_date_time'],
            },
        ),
        migrations.CreateModel(
            name='ParkingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(verbose_name='تاریخ آمار')),
                ('total_in_queue', models.IntegerField(default=0, verbose_name='مجموع در صف')),
                ('total_out_queue', models.IntegerField(default=0, verbose_name='مجموع خارج شده')),
                ('avg_waiting_hours', models.FloatField(default=0, verbose_name='میانگین زمان انتظار')),
                ('max_waiting_hours', models.FloatField(default=0, verbose_name='حداکثر زمان انتظار')),
                ('stats_by_procedure', models.JSONField(default=dict, verbose_name='آمار بر اساس رویه')),
                ('stats_by_load', models.JSONField(default=dict, verbose_name='آمار بر اساس بار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'آمار پارکینگ',
                'verbose_name_plural': 'آمارهای پارکینگ',
                'db_table': 'tirpark_statistics',
                'ordering': ['-stat_date'],
            },
        ),
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ همگام\u200cسازی')),
                ('pages_fetched', models.IntegerField(default=0, verbose_name='تعداد صفحات دریافت شده')),
                ('records_fetched', models.IntegerField(default=0, verbose_name='تعداد رکوردهای دریافت شده')),
                ('records_created', models.IntegerField(default=0, verbose_name='تعداد رکوردهای جدید')),
                ('records_updated', models.IntegerField(default=0, verbose_name='تعداد رکوردهای بروزشده')),
                ('records_skipped', models.IntegerField(default=0, verbose_name='تعداد رکوردهای نادیده گرفته شده')),
                ('status', models.CharField(choices=[('pending', 'در حال انجام'), ('processing', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق'), ('partial', 'بخشی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('duration_seconds', models.FloatField(default=0, verbose_name='مدت زمان بر حسب ثانیه')),
                ('sync_type', models.CharField(default='auto', max_length=50, verbose_name='نوع همگام\u200cسازی')),
                ('metadata', models.JSONField(default=dict, verbose_name='اطلاعات اضافی')),
            ],
            options={
                'verbose_name': 'تاریخچه همگام\u200cسازی',
                'verbose_name_plural': 'تاریخچه همگام\u200cسازی\u200cها',
                'db_table': 'tirpark_sync_history',
                'ordering': ['-sync_date'],
            },
        ),
        migrations.CreateModel(
            name='TruckPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_section', models.CharField(max_length=10, verbose_name='بخش مکانی')),
                ('serial_section', models.CharField(max_length=20, verbose_name='سریال')),
                ('letter_section', models.CharField(max_length=5, verbose_name='حرف')),
                ('code_section', models.CharField(max_length=10, verbose_name='کد')),
                ('full_plate', models.CharField(max_length=50, unique=True, verbose_name='پلاک کامل')),
            ],
            options={
                'verbose_name': 'پلاک خودرو',
                'verbose_name_plural': 'پلاک\u200cهای خودرو',
                'db_table': 'tirpark_truck_plates',
            },
        ),
        migrations.AddIndex(
            model_name='truckplate',
            index=models.Index(fields=['full_plate'], name='tirpark_tru_full_pl_4fe53f_idx'),
        ),
        migrations.AddIndex(
            model_name='truckplate',
            index=models.Index(fields=['location_section', 'serial_section'], name='tirpark_tru_locatio_6b4b1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingstatistics',
            unique_together={('stat_date',)},
        ),
        migrations.AddField(
            model_name='parkingqueue',
            name='customs_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_queues', to='tirpark.customsprocedure', verbose_name='رویه گمرکی'),
        ),
        migrations.AddField(
            model_name='parkingqueue',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_queues', to='tirpark.driver', verbose_name='راننده'),
        ),
        migrations.AddField(
            model_name='parkingqueue',
            name='load_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parking_queues', to='tirpark.loadtype', verbose_name='نوع بار'),
        ),
        migrations.AddField(
            model_name='parkingqueue',
            name='truck_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_queues', to='tirpark.truckplate', verbose_name='پلاک خودرو'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['full_name'], name='tirpark_dri_full_na_0f3178_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingqueue',
            index=models.Index(fields=['receipt_number'], name='tirpark_par_receipt_bbb1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingqueue',
            index=models.Index(fields=['status', 'entry_date_time'], name='tirpark_par_status_625c39_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingqueue',
            index=models.Index(fields=['entry_date_time'], name='tirpark_par_entry_d_a2e382_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingqueue',
            index=models.Index(fields=['sync_date'], name='tirpark_par_sync_da_14d4a8_idx'),
        ),
    ]
