# Generated by Django 4.2 on 2025-09-29 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام نمایشگاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('number_room', models.PositiveIntegerField(verbose_name='تعداد غرفه')),
                ('number_width', models.PositiveIntegerField(verbose_name='عرض ماتریس')),
                ('number_height', models.PositiveIntegerField(verbose_name='ارتفاع ماتریس')),
            ],
            options={
                'verbose_name': 'نمایشگاه',
                'verbose_name_plural': 'نمایشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام غرفه')),
                ('nabsh', models.BooleanField(default=True, verbose_name='نقش دارد')),
                ('metraj', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='متراژ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت')),
                ('is_label', models.BooleanField(default=False, verbose_name='لیبل دارد')),
                ('status', models.IntegerField(choices=[(0, 'آزاد'), (1, 'رزرو شده'), (2, 'قطعی شده'), (3, 'غیرقابل فروش')], default=0, verbose_name='وضعیت')),
                ('w_i', models.PositiveIntegerField(verbose_name='موقعیت در عرض')),
                ('h_i', models.PositiveIntegerField(verbose_name='موقعیت در ارتفاع')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='festival.festival', verbose_name='نمایشگاه')),
            ],
            options={
                'verbose_name': 'غرفه',
                'verbose_name_plural': 'غرفه\u200cها',
                'unique_together': {('festival', 'w_i', 'h_i')},
            },
        ),
    ]
