# Generated by Django 4.2 on 2025-09-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='nabsh',
            field=models.BooleanField(default=True, verbose_name='نبش دارد'),
        ),
    ]
