# Generated by Django 4.2 on 2025-10-01 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festival', '0002_alter_room_nabsh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن ثابت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام شرکت/مؤسسه')),
                ('company_registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره ثبت شرکت')),
                ('activity_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوع فعالیت')),
                ('receipt_image', models.ImageField(upload_to='receipts/%Y/%m/%d/', verbose_name='تصویر فیش واریزی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('status', models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'تایید شده'), (2, 'رد شده'), (3, 'لغو شده')], default=0, verbose_name='وضعیت رزرو')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ رزرو')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='festival.room', verbose_name='غرفه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
            },
        ),
    ]
