# Generated by Django 4.2 on 2025-09-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bider',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_time_online',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='num_bid',
        ),
    ]
