# Generated by Django 4.2 on 2026-05-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_myuser_bider_remove_myuser_last_time_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
