# Generated by Django 4.2 on 2026-05-26 19:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان فصل')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'فصل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آزمون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='مدت زمان آزمون (دقیقه)')),
                ('allowed_entry_start', models.DateTimeField(verbose_name='ساعت مجاز برای ورود به آزمون (از)')),
                ('allowed_entry_end', models.DateTimeField(verbose_name='ساعت مجاز برای ورود به آزمون (تا)')),
                ('is_limited', models.BooleanField(default=False, verbose_name='آیا برگزاری محدود دارد؟')),
                ('allow_go_back', models.BooleanField(default=True, verbose_name='امکان بازگشت به سوال قبل')),
                ('total_questions_count', models.PositiveIntegerField(verbose_name='تعداد سوالات آزمون')),
                ('easy_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد سوالات آسان')),
                ('medium_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد سوالات متوسط')),
                ('hard_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد سوالات سخت')),
                ('randomize_questions', models.BooleanField(default=True, verbose_name='آزمون به صورت رندم ایجاد شود')),
                ('randomize_options', models.BooleanField(default=False, verbose_name='پاسخ\u200cها به صورت رندوم گزینه\u200cها جابجا شوند')),
                ('show_answer_key_immediately', models.BooleanField(default=False, verbose_name='پاسخ\u200cنامه بلافاصله بعد از آزمون در دسترس باشد')),
                ('show_score_immediately', models.BooleanField(default=True, verbose_name='نمایش نمره آزمون بلافاصله نمایش داده شود')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پایه')),
                ('level', models.CharField(choices=[('elementary', 'دبستان'), ('middle', 'متوسطه اول'), ('high', 'متوسطه دوم'), ('pre_university', 'پیش دانشگاهی')], max_length=20, verbose_name='مقطع تحصیلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'پایه تحصیلی',
                'verbose_name_plural': 'پایه\u200cهای تحصیلی',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=10, verbose_name='درجه سختی')),
                ('estimated_time', models.PositiveIntegerField(help_text='ثانیه', verbose_name='مدت زمان لازم برای پاسخ دادن (ثانیه)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lms.models.question_image_path)),
                ('explanation', models.TextField(blank=True, verbose_name='توضیح پاسخ')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.chapter', verbose_name='عنوان فصل')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.grade', verbose_name='پایه تحصیلی')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'بانک سوالات',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن گزینه')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lms.models.option_image_path)),
                ('is_correct', models.BooleanField(default=False, verbose_name='گزینه صحیح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lms.question')),
            ],
            options={
                'verbose_name': 'گزینه سوال',
                'verbose_name_plural': 'گزینه\u200cهای سوال',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='شماره همراه')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=lms.models.teacher_profile_path)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'معلمان',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام درس')),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='lms.grade')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='شماره همراه')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.grade', verbose_name='پایه تحصیلی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دانش\u200cآموز',
                'verbose_name_plural': 'دانش\u200cآموزان',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.subject', verbose_name='عنوان درس'),
        ),
        migrations.AddField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.teacher'),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='نمره کسب شده')),
                ('total_correct', models.PositiveIntegerField(default=0, verbose_name='تعداد پاسخ صحیح')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='تعداد کل سوالات')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('timeout', 'زمان تمام شده')], default='in_progress', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.student')),
            ],
            options={
                'verbose_name': 'شرکت در آزمون',
                'verbose_name_plural': 'شرکت\u200cهای در آزمون',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='invited_students',
            field=models.ManyToManyField(blank=True, related_name='invited_exams', to='lms.student', verbose_name='دانش\u200cآموزان شرکت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='lms.teacher'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.grade', verbose_name='پایه تحصیلی'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lms.subject'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('answer_time', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.questionoption')),
            ],
            options={
                'verbose_name': 'پاسخ دانش\u200cآموز',
                'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب سوال در آزمون این دانش\u200cآموز')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_selections', to='lms.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='lms.student')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam', 'student', 'question')},
            },
        ),
    ]
