# Generated by Django 4.2 on 2026-05-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام مهارت')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام انگلیسی')),
                ('icon', models.CharField(default='📚', max_length=10, verbose_name='آیکون')),
                ('category', models.CharField(default='عمومی', max_length=50, verbose_name='دسته\u200cبندی')),
                ('color', models.CharField(default='#10B981', max_length=20, verbose_name='رنگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='lms/teachers/certificates/', verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, choices=[('0-1', 'کمتر از ۱ سال'), ('1-3', '۱ تا ۳ سال'), ('3-5', '۳ تا ۵ سال'), ('5-10', '۵ تا ۱۰ سال'), ('10+', 'بیش از ۱۰ سال')], max_length=10, null=True, verbose_name='سابقه تدریس'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('doctorate', 'دکترا')], max_length=20, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام مدرسه'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='lms.skill', verbose_name='مهارت\u200cها'),
        ),
    ]
