# Generated by Django 4.2 on 2026-05-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_skill_teacher_certificate_teacher_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.chapter', verbose_name='عنوان فصل'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن گزینه'),
        ),
    ]
