# Generated by Django 4.2 on 2026-06-06 17:11

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.JSONField(default=dict, help_text="نام پروژه به زبان\u200cهای مختلف: {'fa': '...', 'en': '...', 'ar': '...'}")),
                ('description', models.JSONField(default=dict, help_text='توضیح کوتاه به زبان\u200cهای مختلف')),
                ('long_description', models.JSONField(blank=True, default=dict, help_text='توضیح کامل به زبان\u200cهای مختلف', null=True)),
                ('images', models.JSONField(default=list, help_text='لیست آدرس تصاویر پروژه')),
                ('demo_link', models.URLField(blank=True, max_length=500, null=True)),
                ('features', models.JSONField(default=list, help_text="لیست ویژگی\u200cها به زبان\u200cهای مختلف: [{'fa': '...', 'en': '...'}, ...]")),
                ('order', models.IntegerField(default=0, help_text='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio.models.project_image_path)),
                ('alt_text', models.JSONField(blank=True, default=dict, help_text='متن جایگزین به زبان\u200cهای مختلف')),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_objects', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
