# Generated by Django 4.2 on 2026-06-06 17:21

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.RemoveField(
            model_name='project',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Short Description (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_fa',
            field=models.TextField(default=1, verbose_name='توضیح کوتاه (فارسی)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='long_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Full Description (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='long_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کامل (فارسی)'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(default=1, max_length=200, verbose_name='Project Name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name_fa',
            field=models.CharField(default=1, max_length=200, verbose_name='نام پروژه (فارسی)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectimage',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt Text (English)'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='alt_text_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین (فارسی)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک دمو / Demo Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / Active'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.project_image_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project'),
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان ویژگی (فارسی)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Feature Title (English)')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'ordering': ['order'],
            },
        ),
    ]
